### ISSUE TITLE
code for comparison

### ISSUE THREAD

**Issue by dialuser** [icon-lab/SynDiff#12]
Hello thank you very for open sourcing your code. 
I wonder if you can also upload the model codes you used for comparison in the paper, especially I'm interested in your DDPM implementation. Thanks a lot.

**Comment by onat-dalmaz** [comment]
Thank you for your interest in our work and for bringing this up. Unfortunately, we cannot provide the DDPM implementation code as it is based on proprietary code released by the authors of the DDPM paper. You can refer to https://github.com/openai/improved-diffusion for that repository. The original form of this code is for performing unconditional image synthesis. To make it compatible with unsupervised image-to-image translation, you can refer to SynDiff codebase.

We hope this codebase would be useful for your research. If you have any other questions or concerns, please feel free to ask.

**Comment by guanzhenghua** [comment]
@dialuser 
For the question you raised, have you found the corresponding code or paper? If so, could you share it with me.
You can contact me at my email address if it is convenient:  guanzhenghua2022@email.szu.edu.cn
Look forward to yours very much

**Comment by guanzhenghua** [comment]
@dialuser
For the question you raised, have you found the corresponding code or paper? If so, could you share it with me.
You can contact me at my email address if it is convenient: [guanzhenghua2022@email.szu.edu.cn](mailto:guanzhenghua2022@email.szu.edu.cn)
I am looking forward to your reply.
