### ISSUE TITLE
Question about model performance on other dataset

### ISSUE THREAD

**Issue by chengyu89527** [icon-lab/SynDiff#20]
Hi, When I used the IXI dataset ,your model works well, However when I applied your work on WMH(https://wmh.isi.uu.nl/), I met some issues. Some lession part appeared and disappeared randomly. please tell me if it could be solved with some new  technology in your cycle framework. Thanks a lot.
![image](https://github.com/icon-lab/SynDiff/assets/20683039/fe9380b4-71b1-4c4d-9617-a92da7d9b60c)

**Comment by onat-dalmaz** [comment]
Hello, thank you for your interest in our work. We are glad to hear that our model works well on the IXI dataset. However, we have not tested our model on the WMH dataset1, which is a different domain from the IXI dataset. The WMH dataset contains images of patients with white matter hyperintensities (WMH), which are areas of the brain that have been damaged by ischemic injury or small vessel disease. These lesions may affect the image quality and the translation performance of our model.

Our model is based on cycle-consistent adversarial networks, which is a framework for unpaired image-to-image translation. The idea is to learn two mappings between two image domains, such that the distribution of translated images is indistinguishable from the distribution of real images using an adversarial loss. Moreover, to ensure that the translated images preserve the content of the input images, a cycle-consistency loss is used to enforce that the original image can be reconstructed from the translated image and vice versa.

One possible suggestion is to use a paired version of SynDiff, i.e., supervised training improved performance if you have access to a paired image database.

Yet, I can see from the images you attached that the lesions did not disappear in T1-w images, as they are relatively have low contrast for that sequence.

**Comment by chengyu89527** [comment]
Hello：
Really thanks for your reply!!! I try the most trivial version of cyclegan to tansfer the images.Even if it can't gaurantee the disease shape consistent 100%,it's still much better than syndiff. The syndiff seems have a larger imagination space(easy to generator an alter shape) I can only guess, the reason maybe larger model capcity or diffusion produre. Hope you can share your idea.&nbsp;
By the way we only have unpaired different centors t2flair data from WMH(that one is one version t2f not t1w), the lession segmention will change even it's not appearred. I think unpaired shape constraint transfer model may still be a issue need be developed.
Thanks again, looking for your idea!
Have a good day


成大宇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "icon-lab/SynDiff"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月14日(星期天) 下午3:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [icon-lab/SynDiff] Question about model performance on other dataset (Issue #20)





 
Hello, thank you for your interest in our work. We are glad to hear that our model works well on the IXI dataset. However, we have not tested our model on the WMH dataset1, which is a different domain from the IXI dataset. The WMH dataset contains images of patients with white matter hyperintensities (WMH), which are areas of the brain that have been damaged by ischemic injury or small vessel disease. These lesions may affect the image quality and the translation performance of our model.
 
Our model is based on cycle-consistent adversarial networks, which is a framework for unpaired image-to-image translation. The idea is to learn two mappings between two image domains, such that the distribution of translated images is indistinguishable from the distribution of real images using an adversarial loss. Moreover, to ensure that the translated images preserve the content of the input images, a cycle-consistency loss is used to enforce that the original image can be reconstructed from the translated image and vice versa.
 
One possible suggestion is to use a paired version of SynDiff, i.e., supervised training improved performance if you have access to a paired image database.
 
Yet, I can see from the images you attached that the lesions did not disappear in T1-w images, as they are relatively have low contrast for that sequence.

**Comment by william2ai** [comment]
@chengyu89527 Hi, have you found a model that could handle image translation with disease shape?(like T1 to T2) I'm new with this topic and really looking forward for help! For the dataset of my own is also with disease(no dataset pair), and I'm wondering whether to use GAN or diffusion as my baseline. However, upon to your reply and experiment, it seems traditional cGAN is rather better?

Thanks! Looking for reply
Yours
