### ISSUE TITLE
The server socket cannot be initialized

### ISSUE THREAD

**Issue by xychen2022** [icon-lab/SynDiff#21]
Hi, I got the following distributed learning related problem when running the code using example data. How to solve it? Thanks

[W socket.cpp:401] [c10d] The server socket cannot be initialized on [::]:6021 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:401] [c10d] The server socket has failed to bind to 0.0.0.0:6021 (errno: 98 - Address already in use).
[E socket.cpp:435] [c10d] The server socket has failed to listen on any local network address.

**Comment by onat-dalmaz** [comment]
It seems that cpp packages related to distributed learning are not properly installed. Please check 
torch.multiprocessing
torch.distributed

and their required packages too.
