### ISSUE TITLE
image registration code missing

### ISSUE THREAD

**Issue by Michael-H777** [icon-lab/SynDiff#24]
Hi, 

would you consider releasing code used to register T2 and PD onto T1 for the IXI datset? the orientation, image size/dimension is quite different. 

Michael

**Comment by onat-dalmaz** [comment]
For image registrartions, we have used flirt from FSL library. A sample command from FSL-flirt for registration would be:

"fsl5.0-flirt -in " + input_add + " -ref " + ref_address + " -out " + trans_add + " -omat " + mat_add + " -bins 256 -cost normmi -searchrx -180 180 -searchry -180 180 -searchrz -180 180 -dof 12 -interp spline"

**Comment by Michael-H777** [comment]
Hi, thank you for the response. 

I would like to confirm. The data I downloaded from the official IXI dataset have different orientation. is the reorienting also performed by FSL library? or is it done by hand, before the FSL library? 

the PD and T2 data is oriented the same way, but T1 is not oriented like them.
