### ISSUE TITLE
Dataset details

### ISSUE THREAD

**Issue by zhiyuns** [icon-lab/SynDiff#28]
Hi! I'm really pumped about the job, especially the part where you're using the diffusion model for unsupervised medical image translation. I read in the paper that you're using parts of the BRATS and IXI datasets for training, but the details on those datasets are a bit fuzzy. Could you share the subsets you've picked, or at least the subject IDs you're working with? Thanks a bunch!

**Comment by kisonho** [comment]
Same question here. Please address at least which year of BraTS you are using?

**Comment by tcukur** [comment]
The results in the paper were obtained for BraTS 2018 dataset, within both IXI and BraTS, subjects were selected sequentially within the list of subjects provided in the public datasets.

**Comment by kisonho** [comment]
Could you please provide the volume IDs for the splits (25 training, 5 validation, and 10 testing as mentioned in the paper)?
