### ISSUE TITLE
How to train the model with tif images?

### ISSUE THREAD

**Issue by souravsarkarnew** [icon-lab/SynDiff#37]
I want to train your pre-trained model with radar images with optical images as reference, the main goal is to obtain optical image, given a radar image. Since your data is in .mat format i am unable to figure it out as i dont have experience with matlab. Kindly guide me. Thank you.

**Comment by tcukur** [comment]
Actually, .mat files that we used are following hf5 file standard. So if you convert using your preferred script/programming language from tif to hf5, you could use the models.
