### ISSUE TITLE
Traing issue:“torch.autograd.set_detect_anomaly(True)”

### ISSUE THREAD

**Issue by Luke-Huang-Github** [icon-lab/SynDiff#43]
Environment： GPU： single RTX4090,
Dataset: T1 <-> T2 in IXI dataset
Number of images: 2674 pairs
In "train.py" file, when I deleted this line of code：“torch.autograd.set_detect_anomaly(True)” , the speed of training one eopch is faster , but the result of psnr and ssim get worse sometimes. 
Time consumption in one epoch: [original: about 1.5hour ;  deleted the code: about 36 minutes]
PSNR: [original: 29.5 ;  deleted the code: 25.5]

Could you please tell me how to solve this problem?

**Comment by icecreamlovepudding** [comment]
I meet the same question ,the training speed is so slow.
Training 500 pairs of images, need 7days for only 50epoch,do you know how to solve this question?
Thank you !

**Comment by tcukur** [comment]
Training of diffusion models unfortunately can take a while, in this case there is an unsupervised model with diffusion and non-diffusive compartments, so it is like training a model 4x in size. 2-3 days of training on RTX 4090 isn't unexpected. 

“torch.autograd.set_detect_anomaly(True)” checks for errors (NaN value) generated, so it you remove that flag, they will leak in to corrupt model training and you can see performance losses.
