### ISSUE TITLE
How to select data from the Brats dataset?

### ISSUE THREAD

**Issue by peanutbo** [icon-lab/SynDiff#48]
Thanks for your excellent work.

I encountered some difficulties in searching for the dataset
I have found several papers on MRI synthesis that selected 55 samples from the Brats dataset. Is there a dedicated dataset for MRI synthesis? But I couldn't find this dataset. If not, how did you perform data filtering?

**Comment by HangS666** [comment]
hi，how did you slove this problem? Could you tell with me how you sloved it?

**Comment by tcukur** [comment]
Brats contains many more samples, but typically either sequential or random selection from the larger set is performed.
