### ISSUE TITLE
The issue of training speed

### ISSUE THREAD

**Issue by icecreamlovepudding** [icon-lab/SynDiff#51]
Hi,your work is excellent,and I want to try on my own dataset(CBCT-CT)
   However, during the training process, it would take almost a week for only 50 epochs!
   My training dataset consisted of 500 images and the validation dataset consisted of 20 pairs. The hyperparameters are set according to your article.The GPU is NIVIDIA GeForce RTX2080.
   I really want to know the reason.Look forward to your replay.

**Comment by tcukur** [comment]
Depending on the image resolution and the GPU you are using, that could be about normal. Diffusion models can take a while to train. In our setup with RTX 3090, it takes 2-3 days, could be due to GPU.
