### ISSUE TITLE
Why only use diffusive generater during the test?

### ISSUE THREAD

**Issue by icecreamlovepudding** [icon-lab/SynDiff#52]
like the following code, I want to know why only use diffusive_gen?
 " load_checkpoint(checkpoint_file, gen_diffusive_1,'gen_diffusive_1',epoch=str(epoch_chosen), device = device)"
 " load_checkpoint(checkpoint_file, gen_diffusive_2,'gen_diffusive_2',epoch=str(epoch_chosen), device = device)"
To ensure the fairness, use the gen_non_diffusive and gen_diffusive should be better?(Test target image need to be the standard)
And when we've finished the training, what's the difference betwoon diffusive and non_diffusive generater? they can both translate A to B(B to A)? For example, can I only use the non_diffusive generater to get the target image?

**Comment by tcukur** [comment]
The non-diffusive generator is a simpler GAN model that creates lower quality target images (if you look through the ablation results in the paper), the whole purpose it serves is to enable unsupervised training on unpaired data. Once the model is trained, the diffusive generator is to be used as it offers higher quality output.
