### ISSUE TITLE
The normalization and details of the preprocessing for MRI2CT

### ISSUE THREAD

**Issue by yunghx** [icon-lab/SynDiff#6]
Hi!

Can you kindly describe the pre-processing of this dataset: https://zenodo.org/record/583096#.Y3zDFXbMKF4 

The distribution of the original T2 has a large variation, can you describe which patients are selected and what the preprocessing steps you used for image normalization? 

Best

**Comment by onat-dalmaz** [comment]
Thank you for your comment! Regarding the preprocessing of the pelvic dataset, we selected the first 15 subjects for this study. The dataset contained CT volumes registered onto T2 MRI volumes as publicly shared, so T1 MRI volumes were registered onto T2 MRI volumes for consistency. Registrations were implemented in FSL via affine transformation and mutual information loss. In each subject, each imaging volume was separately normalized to a mean intensity of 1. The maximum voxel intensity across subjects was then normalized to 1 to ensure an intensity range of [0,1]. We hope this information helps clarify the preprocessing steps taken for the dataset used in our study.
