### ISSUE TITLE
Dataloading

### ISSUE THREAD

**Issue by Tonks684** [icon-lab/SynDiff#8]
Amazing work, thank you for your contribution. Would it be possible to upload a dummy .mat file that can be used to replicate the data loading?

**Comment by Tonks684** [comment]
I ask because I faced the same issue as in https://github.com/icon-lab/SynDiff/issues/7 but the suggested fix did not work for me which makes me believe I have not reproduced the input as required. Instead of uploading a dummy .mat file perhaps you could confirm the contents and shape of the dataset return from the dataset.CreateDatasetSynthesis function?

**Comment by Tonks684** [comment]
This is the current error message: 
![image](https://user-images.githubusercontent.com/60216815/207917773-a0351d83-dcb1-4a4b-a738-6bb6caa5df1f.png)

**Comment by onat-dalmaz** [comment]
Thank you for your kind words and feedback. We're glad to hear that you found our work helpful. As per your request for a dummy .mat file, we have uploaded a dummy .mat file to the repository, which should be helpful in replicating our data loading. You can find it in the 'SynDiff_sample_data' folder of the repository. Please let us know if you have any further questions or concerns.
